filter based on build phase

diff --git a/.dcg/buildspec.yaml b/.dcg/buildspec.yaml
--- a/.dcg/buildspec.yaml
+++ b/.dcg/buildspec.yaml
@@ -1,12 +1,20 @@
 version: 0.2
 
 phases:
-  install:
-    commands:
-      - echo "Installing Trivy..."
-      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.2
-
   build:
     commands:
-      - echo "Running Trivy security scan..."
-      - trivy config --skip-dirs examples . 2>&1 | tee trivy_output.txt || true
+      - |
+        if [ "${BUILD_PHASE} == "scan" ]; then
+          echo "Installing Trivy..."
+          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.2
+
+          echo "Running Trivy security scan..."
+          trivy config --skip-dirs examples . 2>&1 | tee trivy_output.txt || true
+        elif [ "${BUILD_PHASE} == "scan" ]; then
+          echo "Uploading module to S3..."
+          echo "${S3_MODULE_BUCKET}/${MODULE_NAME}/${CODEBUILD_RESOLVED_SOURCE_VERSION}"
+          # aws s3 cp terraform-module.zip s3://${S3_MODULE_BUCKET}/${MODULE_NAME}/${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip --region ${AWS_REGION}
+        else;
+          echo "Build phase invalid.. exiting"
+          exit 1
+        fi
